name: Convert DOCX to PDF

on:
  push:
    paths:
      - '**/*.docx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LibreOffice
      run: sudo apt-get update && sudo apt-get install -y libreoffice

    - name: Convert DOCX to PDF
      run: |
        find . -name "*.docx" -exec libreoffice --headless --convert-to pdf {} \;

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Automated PDF conversion'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify on failure
      if: failure()
      uses: some/notification-action@v1
      with:
        message: 'PDF conversion workflow failed'
